name: Daily Update

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 08:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Run update script
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python -V
        pip list
        python update_file.py
      continue-on-error: true

    - name: Check for errors
      if: failure()
      run: |
        echo "Error occurred. Printing last 50 lines of update_file.py:"
        tail -n 50 update_file.py
        echo "Printing environment variables (excluding secrets):"
        env | grep -v -i key
        echo "Printing GitHub event payload:"
        cat $GITHUB_EVENT_PATH
